CREATE TABLE notes (
	id SERIAL PRIMARY KEY,
	book_id INT REFERENCES books(id),
	content TEXT NOT NULL
);

CREATE TABLE books (
	id SERIAL PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	author VARCHAR(50) NOT NULL,
    cover_i VARCHAR(15)
);